name: lean_repo
description: A boilerplate-killer for caching and network synchronization. Supports Stale-While-Revalidate, Cache-First, and Network-Only strategies.
version: 0.0.1
repository: https://github.com/AxelBlaz3/lean_repo.git

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6
